Repository omniocular/omniocular, pull requests merged in 2019-06, with the labels that each got.

#24 Add BERT model for diff tokens
  common/evaluators/bert_evaluator.py
  common/trainers/bert_trainer.py
  datasets/bert_processors/__init__.py
  datasets/bert_processors/abstract_processor.py
  datasets/bert_processors/vulas_diff_token.py
  datasets/vulas_diff_token.py
  datasets/vulas_paired_token.py
  models/diff_token/bert/__init__.py
  models/diff_token/bert/__main__.py
  models/diff_token/bert/args.py
  models/diff_token/bert/model.py
  util/io.py
  util/optimization.py
  util/preprocess.py
  util/tokenization.py
  util/tokenize.py
Labels: enhancement

#30 Fix wordpiece vocabulary being used for pre-training BERT
  embeddings/bert/__main__.py
  embeddings/bert/args.py
  models/diff_token/bert/args.py
  run_pretrain.sh
  util/tokenization.py
Labels: bug

#34 Add hierarchical BERT dataset pre-processing
  common/evaluators/bert_evaluator.py
  common/trainers/bert_trainer.py
  datasets/bert_processors/abstract_processor.py
  datasets/bert_processors/vulas_diff_token.py
  datasets/vulas_diff_token.py
  datasets/vulas_paired_token.py
  models/diff_token/bert/hrmodel.py
  util/tokenization.py
Labels: bug, enhancement

#35 Add padding for HR-BERT input preprocessing
  common/trainers/bert_trainer.py
  datasets/bert_processors/abstract_processor.py
  util/preprocess.py
Labels: bug

#36 Fix padding bugs
  common/evaluators/bert_evaluator.py
  common/trainers/bert_trainer.py
  datasets/bert_processors/abstract_processor.py
  models/diff_token/bert/args.py
  models/diff_token/bert/hrmodel.py
  util/preprocess.py
Labels: bug
